name: Publish to npm

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) --abbrev=0)
          echo "Latest tag is $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Change script permissions
        run: chmod +x ./note-make.sh

      - name: Generate Release notes
        id: release-notes
        run: ./note-make.sh

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.latest_tag }}
          release_name: ${{ steps.get_tag.outputs.latest_tag }}
          body: ${{ steps.release-notes.outputs.CHANGE_LIST }}
          draft: false
          prerelease: false

  publish:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}  # You need to create this secret in your repository settings
